# Generated by Django 5.2.4 on 2025-07-05 12:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_app', '0002_auto_20250705_0938'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('duree', models.CharField(help_text='ex: 60 minutes', max_length=50)),
                ('tarif', models.DecimalField(decimal_places=2, max_digits=6)),
                ('details', models.TextField(blank=True, help_text='Détails supplémentaires')),
            ],
            options={
                'verbose_name': 'Exercice',
                'verbose_name_plural': 'Exercices',
            },
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='exercice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='coach_app.exercice'),
        ),
    ]
