# Generated by Django 5.2.4 on 2025-07-05 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_app', '0003_exercice_rendezvous_exercice'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='duree',
            field=models.CharField(blank=True, help_text="Durée de l'exercice au moment du RDV", max_length=50),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='tarif',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Tarif de l'exercice au moment du RDV", max_digits=6, null=True),
        ),
    ]
