# Generated by Django 5.2.4 on 2025-07-05 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_app', '0004_rendezvous_duree_rendezvous_tarif'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SessionReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_tarif', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions_reservation', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Session de réservation',
                'verbose_name_plural': 'Sessions de réservation',
            },
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rendez_vous', to='coach_app.sessionreservation'),
        ),
    ]
