# Generated by Django 5.2.4 on 2025-07-06 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_app', '0006_rendezvous_notes_personnelles_rendezvous_statut_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteHistorique',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField(verbose_name='Contenu de la note')),
                ('date_creation', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('rendez_vous', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes_historique', to='coach_app.rendezvous')),
            ],
            options={
                'verbose_name': 'Note historique',
                'verbose_name_plural': 'Notes historiques',
                'ordering': ['-date_creation'],
            },
        ),
    ]
