# Generated by Django 5.2.4 on 2025-07-06 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_app', '0007_notehistorique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RDVTemporaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('heure', models.CharField(help_text='Format: HH:MM', max_length=5)),
                ('duree', models.CharField(blank=True, max_length=50)),
                ('tarif', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('exercice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdv_temporaires', to='coach_app.exercice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rdv_temporaires', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rendez-vous temporaire',
                'verbose_name_plural': 'Rendez-vous temporaires',
                'unique_together': {('user', 'date', 'heure')},
            },
        ),
    ]
