# Generated by Django 5.2.4 on 2025-07-06 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coach_app', '0008_rdvtemporaire'),
    ]

    operations = [
        migrations.AddField(
            model_name='rdvtemporaire',
            name='rdv_origine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modifications_temp', to='coach_app.rendezvous'),
        ),
    ]
